<a href="https://colab.research.google.com/github/YoshGreen/PROYECTO-FINAL-IA-INF---372-DAT---245/blob/main/IAPF.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#¿Qué hace?
*   Importa pandas para manejar datos en forma de tablas.
*   Importa numpy para operaciones numéricas y verificación de valores inválidos.

#¿Por qué es necesaria?
Porque todo el preprocesamiento y análisis se basa en manipulación de datos tabulares y operaciones matemáticas.

In [ ]:
import pandas as pd
import numpy as np

#¿Qué hace?
*   Carga el dataset desde el archivo CSV.
*   Muestra las primeras filas para verificar que los datos se leyeron correctamente.
#¿Por qué es importante?
Permite validar:
*   número de columnas
*   formato
*   nombres correctos
*   valores razonables.

In [ ]:
path = "/content/data.csv"
df = pd.read_csv(path)

print("Shape:", df.shape)
df.head()


Shape: (569, 33)


id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

#¿Qué hace?
Cuenta cuántos valores nulos existen por columna.
#¿Por qué es importante?
Porque:
*   los modelos de IA no aceptan valores faltantes
*   necesitamos saber si debemos imputar o no.

In [ ]:
print("Valores faltantes por columna:")
df.isnull().sum()


Valores faltantes por columna:


id                           0
diagnosis                    0
radius_mean                  0
texture_mean                 0
perimeter_mean               0
area_mean                    0
smoothness_mean              0
compactness_mean             0
concavity_mean               0
concave points_mean          0
symmetry_mean                0
fractal_dimension_mean       0
radius_se                    0
texture_se                   0
perimeter_se                 0
area_se                      0
smoothness_se                0
compactness_se               0
concavity_se                 0
concave points_se            0
symmetry_se                  0
fractal_dimension_se         0
radius_worst                 0
texture_worst                0
perimeter_worst              0
area_worst                   0
smoothness_worst             0
compactness_worst            0
concavity_worst              0
concave points_worst         0
symmetry_worst               0
fractal_dimension_worst      0
Unnamed: 32                569
dtype: int64

#¿Qué hace?
*   Elimina id porque no aporta información predictiva.
*   Convierte la variable objetivo diagnosis a formato numérico.
#¿Por qué es importante?
*   Los modelos trabajan solo con números.
*   id puede introducir ruido si se mantiene.

In [ ]:
# Eliminar ID (no aporta al modelo)
df = df.drop("id", axis=1)

# Convertir diagnosis B/M -> 0/1
df["diagnosis"] = df["diagnosis"].map({"B":0, "M":1})

df.head()


diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0          1        17.99         10.38          122.80     1001.0   
1          1        20.57         17.77          132.90     1326.0   
2          1        19.69         21.25          130.00     1203.0   
3          1        11.42         20.38           77.58      386.1   
4          1        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  texture_worst  perimeter_worst  area_worst  \
0         0.2419  ...          17.33           184.60      2019.0   
1         0.1812  ...          23.41           158.80      1956.0   
2         0.2069  ...          25.53           152.50      1709.0   
3         0.2597  ...          26.50            98.87       567.7   
4         0.1809  ...          16.67           152.20      1575.0   

   smoothness_worst  compactness_worst  concavity_worst  concave points_worst  \
0            0.1622             0.6656           0.7119                0.2654   
1            0.1238             0.1866           0.2416                0.1860   
2            0.1444             0.4245           0.4504                0.2430   
3            0.2098             0.8663           0.6869                0.2575   
4            0.1374             0.2050           0.4000                0.1625   

   symmetry_worst  fractal_dimension_worst  Unnamed: 32  
0          0.4601                  0.11890          NaN  
1          0.2750                  0.08902          NaN  
2          0.3613                  0.08758          NaN  
3          0.6638                  0.17300          NaN  
4          0.2364                  0.07678          NaN  

[5 rows x 32 columns]

#¿Qué hace?
*   Fuerza todas las columnas predictoras a tipo numérico.
*   Convierte valores mal interpretados en NaN.
#¿Por qué es importante?
Porque algunos valores pueden:
*   venir como texto
*   tener caracteres invisibles
*   causar errores en escalado y SMOTE.





In [ ]:
for col in df.columns:
    if col != "diagnosis":
        df[col] = pd.to_numeric(df[col], errors="coerce")

df.dtypes


diagnosis                    int64
radius_mean                float64
texture_mean               float64
perimeter_mean             float64
area_mean                  float64
smoothness_mean            float64
compactness_mean           float64
concavity_mean             float64
concave points_mean        float64
symmetry_mean              float64
fractal_dimension_mean     float64
radius_se                  float64
texture_se                 float64
perimeter_se               float64
area_se                    float64
smoothness_se              float64
compactness_se             float64
concavity_se               float64
concave points_se          float64
symmetry_se                float64
fractal_dimension_se       float64
radius_worst               float64
texture_worst              float64
perimeter_worst            float64
area_worst                 float64
smoothness_worst           float64
compactness_worst          float64
concavity_worst            float64
concave points_worst       float64
symmetry_worst             float64
fractal_dimension_worst    float64
Unnamed: 32                float64
dtype: object

#¿Qué hace?
Reemplaza valores faltantes por la mediana de cada columna.
#¿Por qué mediana y no media?
*   Es más robusta frente a valores extremos.
*   Muy usada en datasets biomédicos.

In [ ]:
# Imputación con mediana
df = df.fillna(df.median(numeric_only=True))

print("Faltantes después de imputación:")
df.isnull().sum().sum()


Faltantes después de imputación:


np.int64(569)

#¿Qué hace?
Separa:
*   X → variables predictoras
*   y → variable objetivo
#¿Por qué es importante?
Todos los modelos de scikit-learn requieren esta separación.

In [ ]:
X = df.drop("diagnosis", axis=1)
y = df["diagnosis"]

print("X:", X.shape, "y:", y.shape)


X: (569, 31) y: (569,)


#¿Qué hace?
Elimina columnas con un solo valor en todas las filas.
#¿Por qué es clave?
*   No aportan información.
*   Generan NaN al estandarizar (división entre cero).
*   Rompen SMOTE.

In [ ]:
zero_var_cols = [c for c in X.columns if X[c].nunique() <= 1]
print("Columnas con varianza cero:", zero_var_cols)

X = X.loc[:, X.nunique() > 1]
print("X después de eliminar varianza cero:", X.shape)


Columnas con varianza cero: ['Unnamed: 32']
X después de eliminar varianza cero: (569, 30)


#¿Qué hace?
Escala las variables para que tengan:
*   media = 0
*   desviación estándar = 1
#¿Por qué es importante?
*   Las variables tienen rangos muy distintos.
*   Modelos como KNN, SVM y Regresión Logística lo requieren.

In [ ]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler

# A) Normalización (0-1) - opcional
minmax = MinMaxScaler()
X_minmax = pd.DataFrame(minmax.fit_transform(X), columns=X.columns)

# B) Estandarización (Z-score) - recomendada
scaler = StandardScaler()
X_zscore = pd.DataFrame(scaler.fit_transform(X), columns=X.columns)

print("NaN después de escalar:", X_zscore.isnull().sum().sum())
print("Inf después de escalar:", np.isinf(X_zscore).sum().sum())

X_zscore.head()


NaN después de escalar: 0
Inf después de escalar: 0


radius_mean  texture_mean  perimeter_mean  area_mean  smoothness_mean  \
0     1.097064     -2.073335        1.269934   0.984375         1.568466   
1     1.829821     -0.353632        1.685955   1.908708        -0.826962   
2     1.579888      0.456187        1.566503   1.558884         0.942210   
3    -0.768909      0.253732       -0.592687  -0.764464         3.283553   
4     1.750297     -1.151816        1.776573   1.826229         0.280372   

   compactness_mean  concavity_mean  concave points_mean  symmetry_mean  \
0          3.283515        2.652874             2.532475       2.217515   
1         -0.487072       -0.023846             0.548144       0.001392   
2          1.052926        1.363478             2.037231       0.939685   
3          3.402909        1.915897             1.451707       2.867383   
4          0.539340        1.371011             1.428493      -0.009560   

   fractal_dimension_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0                2.255747  ...      1.886690      -1.359293         2.303601   
1               -0.868652  ...      1.805927      -0.369203         1.535126   
2               -0.398008  ...      1.511870      -0.023974         1.347475   
3                4.910919  ...     -0.281464       0.133984        -0.249939   
4               -0.562450  ...      1.298575      -1.466770         1.338539   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0    2.001237          1.307686           2.616665         2.109526   
1    1.890489         -0.375612          -0.430444        -0.146749   
2    1.456285          0.527407           1.082932         0.854974   
3   -0.550021          3.394275           3.893397         1.989588   
4    1.220724          0.220556          -0.313395         0.613179   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0              2.296076        2.750622                 1.937015  
1              1.087084       -0.243890                 0.281190  
2              1.955000        1.152255                 0.201391  
3              2.175786        6.046041                 4.935010  
4              0.729259       -0.868353                -0.397100  

[5 rows x 30 columns]

#¿Qué hace?
*   Crea nuevas variables a partir de relaciones geométricas.
#¿Por qué es útil?
*   Las proporciones suelen ser más informativas que valores absolutos.
*   Mejora la capacidad predictiva del modelo.

In [ ]:
df_fe = X_zscore.copy()

df_fe["radius_per_area"] = (X["radius_mean"] / (X["area_mean"] + 1e-6)).values
df_fe["compactness_ratio"] = (X["compactness_mean"] / (X["concavity_mean"] + 1e-6)).values

df_fe.head()


radius_mean  texture_mean  perimeter_mean  area_mean  smoothness_mean  \
0     1.097064     -2.073335        1.269934   0.984375         1.568466   
1     1.829821     -0.353632        1.685955   1.908708        -0.826962   
2     1.579888      0.456187        1.566503   1.558884         0.942210   
3    -0.768909      0.253732       -0.592687  -0.764464         3.283553   
4     1.750297     -1.151816        1.776573   1.826229         0.280372   

   compactness_mean  concavity_mean  concave points_mean  symmetry_mean  \
0          3.283515        2.652874             2.532475       2.217515   
1         -0.487072       -0.023846             0.548144       0.001392   
2          1.052926        1.363478             2.037231       0.939685   
3          3.402909        1.915897             1.451707       2.867383   
4          0.539340        1.371011             1.428493      -0.009560   

   fractal_dimension_mean  ...  perimeter_worst  area_worst  smoothness_worst  \
0                2.255747  ...         2.303601    2.001237          1.307686   
1               -0.868652  ...         1.535126    1.890489         -0.375612   
2               -0.398008  ...         1.347475    1.456285          0.527407   
3                4.910919  ...        -0.249939   -0.550021          3.394275   
4               -0.562450  ...         1.338539    1.220724          0.220556   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0           2.616665         2.109526              2.296076        2.750622   
1          -0.430444        -0.146749              1.087084       -0.243890   
2           1.082932         0.854974              1.955000        1.152255   
3           3.893397         1.989588              2.175786        6.046041   
4          -0.313395         0.613179              0.729259       -0.868353   

   fractal_dimension_worst  radius_per_area  compactness_ratio  
0                 1.937015         0.017972           0.925022  
1                 0.281190         0.015513           0.904938  
2                 0.201391         0.016367           0.810026  
3                 4.935010         0.029578           1.176051  
4                -0.397100         0.015644           0.670704  

[5 rows x 32 columns]

#¿Qué hace?
Divide los datos en:
*   70% entrenamiento
*   30% prueba

Sin aplicar SMOTE

Muestra la distribución real de clases en el conjunto de entrenamiento.

Aplica SMOTE solo al conjunto de entrenamiento.

Muestra la nueva distribución balanceada después de SMOTE.
#¿Por qué?
*   Permite ver explícitamente el desbalance del dataset.
*   Demuestra que SMOTE no se aplica al conjunto de prueba (evita data leakage).
*   Justifica metodológicamente el uso de SMOTE.
*   Es evidencia visual para el informe y la defensa.

In [ ]:
from sklearn.model_selection import train_test_split
from imblearn.over_sampling import SMOTE
import pandas as pd

# Split SIN SMOTE
X_train_ns, X_test_ns, y_train_ns, y_test_ns = train_test_split(
    X_zscore, y, test_size=0.3, random_state=42, stratify=y
)


print("Distribución ORIGINAL en entrenamiento:")
print(y_train_ns.value_counts())

# Aplicar SMOTE SOLO al entrenamiento
sm = SMOTE(random_state=42)
X_train_sm, y_train_sm = sm.fit_resample(X_train_ns, y_train_ns)

print("\nDistribución BALANCEADA con SMOTE (solo entrenamiento):")
print(pd.Series(y_train_sm).value_counts())


Distribución ORIGINAL en entrenamiento:
diagnosis
0    250
1    148
Name: count, dtype: int64

Distribución BALANCEADA con SMOTE (solo entrenamiento):
diagnosis
1    250
0    250
Name: count, dtype: int64


#¿Qué hace?
1. Usa el mismo split que la celda anterior.
2. Entrena el mismo modelo en dos escenarios:
  *   sin SMOTE
  *   con SMOTE
3. Evalúa ambos modelos sobre el mismo conjunto de prueba real.
4. Calcula métricas:
  *   Accuracy
  *   Precision
  *   Recall
  *   F1-score
  *   Matriz de confusión
#¿Por qué es importante?
*   Permite comparar desempeño real, no solo balance de datos.
*   Muestra si SMOTE:
*   mejora recall (detección de malignos),
*   empeora precision,
*   cambia el tipo de errores.
*   Es fundamental en problemas médicos, donde los falsos negativos importan más.

In [ ]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
from sklearn.tree import DecisionTreeClassifier
from imblearn.over_sampling import SMOTE
from sklearn.model_selection import train_test_split

# Modelo
model = DecisionTreeClassifier(random_state=42)

# ===== ESCENARIO 1: SIN SMOTE =====
model.fit(X_train_ns, y_train_ns)
pred_ns = model.predict(X_test_ns)

print("====== SIN SMOTE ======")
print("Accuracy :", accuracy_score(y_test_ns, pred_ns))
print("Precision:", precision_score(y_test_ns, pred_ns))
print("Recall   :", recall_score(y_test_ns, pred_ns))
print("F1-score :", f1_score(y_test_ns, pred_ns))
print("Matriz de Confusión:\n", confusion_matrix(y_test_ns, pred_ns))

# ===== ESCENARIO 2: CON SMOTE =====
model.fit(X_train_sm, y_train_sm)
pred_sm = model.predict(X_test_ns)

print("\n====== CON SMOTE ======")
print("Accuracy :", accuracy_score(y_test_ns, pred_sm))
print("Precision:", precision_score(y_test_ns, pred_sm))
print("Recall   :", recall_score(y_test_ns, pred_sm))
print("F1-score :", f1_score(y_test_ns, pred_sm))
print("Matriz de Confusión:\n", confusion_matrix(y_test_ns, pred_sm))


====== SIN SMOTE ======
Accuracy : 0.9005847953216374
Precision: 0.8852459016393442
Recall   : 0.84375
F1-score : 0.864
Matriz de Confusión:
 [[100   7]
 [ 10  54]]

====== CON SMOTE ======
Accuracy : 0.9473684210526315
Precision: 0.9365079365079365
Recall   : 0.921875
F1-score : 0.9291338582677166
Matriz de Confusión:
 [[103   4]
 [  5  59]]


#¿Qué hace?
Esta celda define y evalúa distintos algoritmos de clasificación supervisada:
*   Árbol de Decisión
*   K-Nearest Neighbors (KNN)
*   Regresión Logística
*   Naive Bayes
*   Support Vector Machine (SVM)

Cada modelo se entrena utilizando el conjunto de entrenamiento original sin aplicar SMOTE y se evalúa sobre el mismo conjunto de prueba. Para cada modelo se calculan métricas de desempeño como:
*   Accuracy
*   Precision
*   Recall
*   F1-score
*   Matriz de confusión

Finalmente, los resultados se almacenan en una tabla comparativa que permite contrastar el desempeño de todos los modelos evaluados.
#¿Por qué?
*   Permite comparar distintos enfoques de clasificación bajo las mismas condiciones experimentales.
*   Garantiza una evaluación justa, ya que todos los modelos usan el mismo conjunto de entrenamiento y prueba.
*   Proporciona una línea base realista del desempeño de los modelos utilizando datos reales, sin técnicas de balanceo artificial.
*   Facilita la selección del modelo más adecuado para el problema de clasificación médica.

In [ ]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
import pandas as pd

# Definición de modelos
modelos = {
    "Árbol de Decisión": DecisionTreeClassifier(random_state=42),
    "KNN": KNeighborsClassifier(n_neighbors=5),
    "Regresión Logística": LogisticRegression(max_iter=2000),
    "Naive Bayes": GaussianNB(),
    "SVM": SVC(kernel="linear")
}

resultados = []

for nombre, modelo in modelos.items():
    # Entrenamiento SIN SMOTE (datos reales)
    modelo.fit(X_train_ns, y_train_ns)
    pred = modelo.predict(X_test_ns)

    # Métricas
    acc = accuracy_score(y_test_ns, pred)
    prec = precision_score(y_test_ns, pred)
    rec = recall_score(y_test_ns, pred)
    f1 = f1_score(y_test_ns, pred)
    cm = confusion_matrix(y_test_ns, pred)

    resultados.append([nombre, acc, prec, rec, f1])

    print("\n==============================")
    print("Modelo:", nombre)
    print("==============================")
    print("Matriz de Confusión:\n", cm)
    print(f"Accuracy:  {acc:.4f}")
    print(f"Precision: {prec:.4f}")
    print(f"Recall:    {rec:.4f}")
    print(f"F1-Score:  {f1:.4f}")

# Tabla comparativa final
df_resultados = pd.DataFrame(
    resultados,
    columns=["Modelo", "Accuracy", "Precision", "Recall", "F1"]
)

df_resultados



Modelo: Árbol de Decisión
Matriz de Confusión:
 [[101   7]
 [  3  60]]
Accuracy:  0.9415
Precision: 0.8955
Recall:    0.9524
F1-Score:  0.9231

Modelo: KNN
Matriz de Confusión:
 [[105   3]
 [  4  59]]
Accuracy:  0.9591
Precision: 0.9516
Recall:    0.9365
F1-Score:  0.9440

Modelo: Regresión Logística
Matriz de Confusión:
 [[106   2]
 [  1  62]]
Accuracy:  0.9825
Precision: 0.9688
Recall:    0.9841
F1-Score:  0.9764

Modelo: Naive Bayes
Matriz de Confusión:
 [[103   5]
 [  6  57]]
Accuracy:  0.9357
Precision: 0.9194
Recall:    0.9048
F1-Score:  0.9120

Modelo: SVM
Matriz de Confusión:
 [[106   2]
 [  2  61]]
Accuracy:  0.9766
Precision: 0.9683
Recall:    0.9683
F1-Score:  0.9683


Modelo  Accuracy  Precision    Recall        F1
0    Árbol de Decisión  0.941520   0.895522  0.952381  0.923077
1                  KNN  0.959064   0.951613  0.936508  0.944000
2  Regresión Logística  0.982456   0.968750  0.984127  0.976378
3          Naive Bayes  0.935673   0.919355  0.904762  0.912000
4                  SVM  0.976608   0.968254  0.968254  0.968254

#¿Qué hace?
Esta celda define una función que evalúa el desempeño de un modelo de clasificación utilizando múltiples divisiones aleatorias del dataset.
Para cada iteración:
1. Se divide el dataset en entrenamiento y prueba según una proporción definida (por ejemplo 80/20 o 50/50).
2. Opcionalmente, se aplica la técnica SMOTE solo al conjunto de entrenamiento.
3. Se entrena un modelo SVM con kernel lineal.
4. Se evalúa el modelo sobre el conjunto de prueba y se calcula la exactitud (accuracy).

Este proceso se repite 100 veces y la función devuelve la mediana de las exactitudes obtenidas.

#¿Por qué?
*   Reduce la dependencia de un único split entrenamiento/prueba.
*   Permite evaluar la estabilidad y robustez del modelo frente a diferentes particiones de los datos.
*   El uso de la mediana proporciona una medida más robusta que el promedio, evitando la influencia de valores atípicos.
*   Cumple con los criterios de validación solicitados en el enunciado académico del proyecto.

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.svm import SVC
from imblearn.over_sampling import SMOTE
import numpy as np

def evaluar_modelo_correcto(X, y, test_size, usar_smote=False, n_reps=100):
    accuracies = []

    for i in range(n_reps):
        # 1. Split primero (datos reales)
        X_train, X_test, y_train, y_test = train_test_split(
            X, y,
            test_size=test_size,
            random_state=i,
            stratify=y
        )

        # 2. SMOTE SOLO en entrenamiento
        if usar_smote:
            sm = SMOTE(random_state=i)
            X_train, y_train = sm.fit_resample(X_train, y_train)

        # 3. Entrenar modelo
        modelo = SVC(kernel="linear")
        modelo.fit(X_train, y_train)

        # 4. Evaluar
        y_pred = modelo.predict(X_test)
        acc = accuracy_score(y_test, y_pred)
        accuracies.append(acc)

    return np.median(accuracies)


#¿Qué hace?
Esta celda utiliza la función definida previamente para evaluar el modelo bajo distintos escenarios experimentales:
*   División 80% entrenamiento / 20% prueba sin SMOTE.
*   División 50% entrenamiento / 50% prueba sin SMOTE.
*   División 80% entrenamiento / 20% prueba aplicando SMOTE solo al entrenamiento.
*   División 50% entrenamiento / 50% prueba aplicando SMOTE solo al entrenamiento.
Para cada caso se calcula la mediana de la exactitud obtenida tras 100 iteraciones y se muestran los resultados por pantalla.
#¿Por qué?
*   Permite analizar cómo influye la proporción de datos de entrenamiento y prueba en el desempeño del modelo.
*   Evalúa el impacto del balanceo de clases mediante SMOTE en distintos escenarios.
*   Proporciona una validación más robusta y confiable del modelo, especialmente relevante en contextos médicos.
*   Ayuda a determinar si el uso de SMOTE mejora la estabilidad o el rendimiento del clasificador.

In [ ]:
# SIN SMOTE
med_80_20_no = evaluar_modelo_correcto(X_zscore, y, test_size=0.2, usar_smote=False)
med_50_50_no = evaluar_modelo_correcto(X_zscore, y, test_size=0.5, usar_smote=False)

# CON SMOTE (solo entrenamiento)
med_80_20_sm = evaluar_modelo_correcto(X_zscore, y, test_size=0.2, usar_smote=True)
med_50_50_sm = evaluar_modelo_correcto(X_zscore, y, test_size=0.5, usar_smote=True)

print("SIN SMOTE")
print("Mediana Accuracy 80/20:", med_80_20_no)
print("Mediana Accuracy 50/50:", med_50_50_no)

print("\nCON SMOTE")
print("Mediana Accuracy 80/20:", med_80_20_sm)
print("Mediana Accuracy 50/50:", med_50_50_sm)


SIN SMOTE
Mediana Accuracy 80/20: 0.9736842105263158
Mediana Accuracy 50/50: 0.968421052631579

CON SMOTE
Mediana Accuracy 80/20: 0.9736842105263158
Mediana Accuracy 50/50: 0.9649122807017544


#Guardar el archivo ya preprocesado

In [ ]:
df_resultados.to_csv("resultados_modelos_todas_columnas.csv", index=False)
print("Archivo guardado: resultados_modelos_todas_columnas.csv")
